export interface Gardener {
  Archiv: string,
  Autor: string,
  Band: string,
  Dokumententyp: string,
  ID: number,
  Inhalt: string,
  Jahr: string,
  Nummer: string,
  Person: string,
  Seite: string,
  Signatur: string,
  Zeitschrift: string,
  created: string,
  location: string,
  reserve01:string,
  reserve02: string,
  sourcefile: string,
  updated: string
}