/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Gardener } from "./utils/interfaces";
export namespace Components {
    interface AppLoading {
        "visible": boolean;
    }
    interface AppMessages {
    }
    interface GardbDetail {
        "close": () => Promise<void>;
        "record": Gardener;
    }
    interface GardbFilters {
        "results": any;
    }
    interface GardbPagination {
        "currentPage": number;
        "pages": number;
    }
    interface GardbResults {
    }
    interface GardbRoot {
    }
    interface GardbSearch {
        "api": string;
    }
}
declare global {
    interface HTMLAppLoadingElement extends Components.AppLoading, HTMLStencilElement {
    }
    var HTMLAppLoadingElement: {
        prototype: HTMLAppLoadingElement;
        new (): HTMLAppLoadingElement;
    };
    interface HTMLAppMessagesElement extends Components.AppMessages, HTMLStencilElement {
    }
    var HTMLAppMessagesElement: {
        prototype: HTMLAppMessagesElement;
        new (): HTMLAppMessagesElement;
    };
    interface HTMLGardbDetailElement extends Components.GardbDetail, HTMLStencilElement {
    }
    var HTMLGardbDetailElement: {
        prototype: HTMLGardbDetailElement;
        new (): HTMLGardbDetailElement;
    };
    interface HTMLGardbFiltersElement extends Components.GardbFilters, HTMLStencilElement {
    }
    var HTMLGardbFiltersElement: {
        prototype: HTMLGardbFiltersElement;
        new (): HTMLGardbFiltersElement;
    };
    interface HTMLGardbPaginationElement extends Components.GardbPagination, HTMLStencilElement {
    }
    var HTMLGardbPaginationElement: {
        prototype: HTMLGardbPaginationElement;
        new (): HTMLGardbPaginationElement;
    };
    interface HTMLGardbResultsElement extends Components.GardbResults, HTMLStencilElement {
    }
    var HTMLGardbResultsElement: {
        prototype: HTMLGardbResultsElement;
        new (): HTMLGardbResultsElement;
    };
    interface HTMLGardbRootElement extends Components.GardbRoot, HTMLStencilElement {
    }
    var HTMLGardbRootElement: {
        prototype: HTMLGardbRootElement;
        new (): HTMLGardbRootElement;
    };
    interface HTMLGardbSearchElement extends Components.GardbSearch, HTMLStencilElement {
    }
    var HTMLGardbSearchElement: {
        prototype: HTMLGardbSearchElement;
        new (): HTMLGardbSearchElement;
    };
    interface HTMLElementTagNameMap {
        "app-loading": HTMLAppLoadingElement;
        "app-messages": HTMLAppMessagesElement;
        "gardb-detail": HTMLGardbDetailElement;
        "gardb-filters": HTMLGardbFiltersElement;
        "gardb-pagination": HTMLGardbPaginationElement;
        "gardb-results": HTMLGardbResultsElement;
        "gardb-root": HTMLGardbRootElement;
        "gardb-search": HTMLGardbSearchElement;
    }
}
declare namespace LocalJSX {
    interface AppLoading {
        "visible"?: boolean;
    }
    interface AppMessages {
    }
    interface GardbDetail {
        "onRecordSelected"?: (event: CustomEvent<Gardener>) => void;
        "record"?: Gardener;
    }
    interface GardbFilters {
        "onFilterEvent"?: (event: CustomEvent<any>) => void;
        "onRecordSelected"?: (event: CustomEvent<any>) => void;
        "results"?: any;
    }
    interface GardbPagination {
        "currentPage"?: number;
        "onPageSelected"?: (event: CustomEvent<any>) => void;
        "pages"?: number;
    }
    interface GardbResults {
        "onRecordSelected"?: (event: CustomEvent<Gardener>) => void;
    }
    interface GardbRoot {
    }
    interface GardbSearch {
        "api"?: string;
    }
    interface IntrinsicElements {
        "app-loading": AppLoading;
        "app-messages": AppMessages;
        "gardb-detail": GardbDetail;
        "gardb-filters": GardbFilters;
        "gardb-pagination": GardbPagination;
        "gardb-results": GardbResults;
        "gardb-root": GardbRoot;
        "gardb-search": GardbSearch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-loading": LocalJSX.AppLoading & JSXBase.HTMLAttributes<HTMLAppLoadingElement>;
            "app-messages": LocalJSX.AppMessages & JSXBase.HTMLAttributes<HTMLAppMessagesElement>;
            "gardb-detail": LocalJSX.GardbDetail & JSXBase.HTMLAttributes<HTMLGardbDetailElement>;
            "gardb-filters": LocalJSX.GardbFilters & JSXBase.HTMLAttributes<HTMLGardbFiltersElement>;
            "gardb-pagination": LocalJSX.GardbPagination & JSXBase.HTMLAttributes<HTMLGardbPaginationElement>;
            "gardb-results": LocalJSX.GardbResults & JSXBase.HTMLAttributes<HTMLGardbResultsElement>;
            "gardb-root": LocalJSX.GardbRoot & JSXBase.HTMLAttributes<HTMLGardbRootElement>;
            "gardb-search": LocalJSX.GardbSearch & JSXBase.HTMLAttributes<HTMLGardbSearchElement>;
        }
    }
}
