/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface GardenerDetail {
    'record': any;
  }
  interface GardenerResults {
    'results': any;
  }
  interface GardenerSearch {
    'api': string;
  }
}

declare global {


  interface HTMLGardenerDetailElement extends Components.GardenerDetail, HTMLStencilElement {}
  var HTMLGardenerDetailElement: {
    prototype: HTMLGardenerDetailElement;
    new (): HTMLGardenerDetailElement;
  };

  interface HTMLGardenerResultsElement extends Components.GardenerResults, HTMLStencilElement {}
  var HTMLGardenerResultsElement: {
    prototype: HTMLGardenerResultsElement;
    new (): HTMLGardenerResultsElement;
  };

  interface HTMLGardenerSearchElement extends Components.GardenerSearch, HTMLStencilElement {}
  var HTMLGardenerSearchElement: {
    prototype: HTMLGardenerSearchElement;
    new (): HTMLGardenerSearchElement;
  };
  interface HTMLElementTagNameMap {
    'gardener-detail': HTMLGardenerDetailElement;
    'gardener-results': HTMLGardenerResultsElement;
    'gardener-search': HTMLGardenerSearchElement;
  }
}

declare namespace LocalJSX {
  interface GardenerDetail {
    'onRecordSelected'?: (event: CustomEvent<any>) => void;
    'record'?: any;
  }
  interface GardenerResults {
    'onRecordSelected'?: (event: CustomEvent<any>) => void;
    'results'?: any;
  }
  interface GardenerSearch {
    'api'?: string;
  }

  interface IntrinsicElements {
    'gardener-detail': GardenerDetail;
    'gardener-results': GardenerResults;
    'gardener-search': GardenerSearch;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'gardener-detail': LocalJSX.GardenerDetail & JSXBase.HTMLAttributes<HTMLGardenerDetailElement>;
      'gardener-results': LocalJSX.GardenerResults & JSXBase.HTMLAttributes<HTMLGardenerResultsElement>;
      'gardener-search': LocalJSX.GardenerSearch & JSXBase.HTMLAttributes<HTMLGardenerSearchElement>;
    }
  }
}


